package com.enterprise.agent.security.agentic;

public enum AgenticRisk {
    INSTRUCTION_OVERRIDE,
    SYSTEM_PROMPT_DISCLOSURE,
    TOOL_COMMAND_IN_DATA,
    DATA_EXFILTRATION,
    PRIVILEGE_ESCALATION,
    MEMORY_POISONING,
    IDENTITY_MISMATCH,
    SCOPE_VIOLATION,
    EGRESS_VIOLATION,
    TOOL_DESCRIPTOR_TAMPERING,
    DANGEROUS_TOOL_CHAIN,
    MESSAGE_TAMPERING,
    REPLAYED_MESSAGE,
    EXPIRED_MESSAGE
}
